# Generated by Django 4.1.1 on 2022-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSearching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='userHtmlUrl',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='URL'),
        ),
    ]
