# Generated by Django 4.1.1 on 2022-09-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSearching', '0002_alter_candidate_userhtmlurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
    ]
