# Generated by Django 4.1.1 on 2022-09-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSearching', '0003_alter_candidate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.CharField(max_length=300, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='blog',
            field=models.CharField(max_length=300, null=True, verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='userHtmlUrl',
            field=models.CharField(max_length=2048, null=True, unique=True, verbose_name='URL'),
        ),
    ]
