# Generated by Django 4.1.1 on 2022-09-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSearching', '0004_alter_candidate_bio_alter_candidate_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.CharField(max_length=500, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='blog',
            field=models.CharField(max_length=500, null=True, verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='company',
            field=models.CharField(max_length=300, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.CharField(max_length=300, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(max_length=300, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
    ]
